services:
  db:
    image: postgres:16-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
    command: ./bin/dev          # Procfile.dev を使う場合（おすすめ）
    # command: bundle exec rails server -b 0.0.0.0 -p 3000
    tty: true
    stdin_open: true

volumes:
  db-data: