services:
  db:
    image: postgres:16-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes: []
    expose:
      - "3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - RAILS_ENV=production
      - DATABASE_URL=postgresql://postgres:password@db:5432/baukis2_production 
      - RAILS_SERVE_STATIC_FILES=true
      - RAILS_HOSTS=web,localhost,127.0.0.1,0.0.0.0  
    restart: unless-stopped

  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "8080:80"
      #- "443:443"
      #- "443:443/udp"   # HTTP/3
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      #- caddy_config:/config
    depends_on:
      - web

volumes:
  db-data:
  caddy_data:
  caddy_config: