# syntax = docker/dockerfile:1

ARG RUBY_VERSION=3.4.5
FROM ruby:$RUBY_VERSION-slim

WORKDIR /rails

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential git libpq-dev libvips pkg-config curl libyaml-dev \
      postgresql-client \
      chromium \ 
      chromium-driver && \
    rm -rf /var/lib/apt/lists/* 

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 3

COPY . .

ENTRYPOINT ["/rails/entrypoint.sh"]
EXPOSE 3000
CMD ["./bin/dev"]

