FROM ruby:3.4.5

WORKDIR /baukis2
COPY Gemfile /baukis2/Gemfile
COPY Gemfile.lock /baukis2/Gemfile.lock
RUN bundle install

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]