# syntax = docker/dockerfile:1
ARG RUBY_VERSION=3.4.5
FROM ruby:$RUBY_VERSION-slim

WORKDIR /rails

# 必要なパッケージ、Node.js、および依存関係のインストール
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    libpq-dev \
    libvips \
    pkg-config \
    libyaml-dev \
    postgresql-client \
    chromium \
    chromium-driver \
    curl \
    nodejs \
    npm && \
    rm -rf /var/lib/apt/lists/*

# Node.js標準のCorepackを有効化し、Yarnを確実にインストール
RUN corepack enable && corepack prepare yarn@stable --activate

COPY Gemfile Gemfile.lock ./
RUN bundle install --jobs 4 --retry 3

COPY . .

ENTRYPOINT ["/rails/entrypoint.sh"]
EXPOSE 3000
CMD ["./bin/dev"]



